name: PHP tests
on: [push, pull_request]

jobs:
  php-linter:
    name: PHP Syntax check (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [5.6, 7.2, 7.3, 7.4, 8.0, 8.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP syntax checker ${{ matrix.php-version }}
        uses: prestashop/github-action-php-lint/${{ matrix.php-version }}@master

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: tleon/.github/.github/actions/php-cs-fixer@Issue-39300-improve-module-ci
        with:
          php-version: '7.4'

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presta-version: ['1.7.6', '1.7.7', '1.7.8', 'latest']
    steps:
      - uses: tleon/.github/.github/actions/phpstan@Issue-39300-improve-module-ci
        with:
          php-version: '7.4'
          presta-version: ${{ matrix.presta-version }}
          module-name: ps_cashondelivery
          phpstan-config: tests/phpstan/phpstan-${{ matrix.presta-version }}.neon